### ISSUE TITLE
how to compute NLL without matching?

### ISSUE THREAD

**Issue by anilbatra2185** [lhj815/D-RMM#1]
Hi @lhj815 ,

Thank you for sharing the code of your interesting work. I enjoyed reading it.

I have a small question about the 1-to-1 mapping between the prediction and GT box to compute the NLL loss. In the [code](https://github.com/lhj815/D-RMM/blob/master/mmdet/models/roi_heads/bbox_heads/dii_drmm_head.py#L281) it looks to me that there exists a 1-to-1 mapping, however it is not clear to me how we obtain it? 

I would appreciate any pointer/code reference. Thanks in advance!

Regards

**Comment by lhj815** [comment]
Hi, thanks for your interest in our paper :)

Loss = NLL loss + $\beta$ $\cdot$ MCM loss
NLL loss : the [former term](https://github.com/lhj815/D-RMM/blob/2c64057451ad2bbf58b5aa69b3556177d76c33d2/mmdet/models/roi_heads/bbox_heads/dii_drmm_head.py#L335)
MCM loss : the [latter term](https://github.com/lhj815/D-RMM/blob/2c64057451ad2bbf58b5aa69b3556177d76c33d2/mmdet/models/roi_heads/bbox_heads/dii_drmm_head.py#L335)

About the [max function](https://github.com/lhj815/D-RMM/blob/2c64057451ad2bbf58b5aa69b3556177d76c33d2/mmdet/models/roi_heads/bbox_heads/dii_drmm_head.py#L333)
- If the 1-to-1 matching you're referring to is the max function, then the max function is intended for calculating the MCM loss, not the NLL loss.

The NLL loss
- When calculating the NLL losses for multiple GT with the mixture model, there is NO 1-to-1 matching. 
  - The calculations of [Categorical](https://github.com/lhj815/D-RMM/blob/2c64057451ad2bbf58b5aa69b3556177d76c33d2/mmdet/models/roi_heads/bbox_heads/dii_drmm_head.py#L320) and [Cauchy](https://github.com/lhj815/D-RMM/blob/2c64057451ad2bbf58b5aa69b3556177d76c33d2/mmdet/models/roi_heads/bbox_heads/dii_drmm_head.py#L306) of NLL are performed by all N-components for a single gt (w/o 1-to-1 matching).
    - [Categorical](https://github.com/lhj815/D-RMM/blob/2c64057451ad2bbf58b5aa69b3556177d76c33d2/mmdet/models/roi_heads/bbox_heads/dii_drmm_head.py#L320) shape
      - gt_onehot_s: (n_gt, n_cls)
      - prob_s: (n_component, n_cls)
      - cat_lh_s : (n_gt, n_component)
        - When calculating the NLL for a single gt, all N-components are involved in the calculation w/o 1-to-1 matching.
    - [Cauchy](https://github.com/lhj815/D-RMM/blob/2c64057451ad2bbf58b5aa69b3556177d76c33d2/mmdet/models/roi_heads/bbox_heads/dii_drmm_head.py#L306) shape
      - gt_box_s: (n_gt, 4)
      - loc_s: (n_component, 4)
      - coord_lh_s: (n_gt, n_component) --> same with Categorical.
  - Likelihood is calculated by the [sum](https://github.com/lhj815/D-RMM/blob/2c64057451ad2bbf58b5aa69b3556177d76c33d2/mmdet/models/roi_heads/bbox_heads/dii_drmm_head.py#L322). (n_gt, n_component) --> (n_gt, 1) ![image](https://github.com/lhj815/D-RMM/assets/51690077/5e447aa8-9b83-43f3-8550-51fcccb8c944)
  - And for all gt, they are later summed up together with all the gts within the mini-batch.([here](https://github.com/lhj815/D-RMM/blob/2c64057451ad2bbf58b5aa69b3556177d76c33d2/mmdet/models/roi_heads/bbox_heads/dii_drmm_head.py#L345)).
     - Note that [here](https://github.com/lhj815/D-RMM/blob/2c64057451ad2bbf58b5aa69b3556177d76c33d2/mmdet/models/roi_heads/bbox_heads/dii_drmm_head.py#L322) refers to the 'sum of the N-components' of the mixture model about each one GT box. 
       - (n_gt, n_component) --> (n_gt, 1)
     - [here](https://github.com/lhj815/D-RMM/blob/2c64057451ad2bbf58b5aa69b3556177d76c33d2/mmdet/models/roi_heads/bbox_heads/dii_drmm_head.py#L345) refers the sum of NLL losses of all component within the mini-batch. 

(It might not be what you're asking, but...) The [for loop](https://github.com/lhj815/D-RMM/blob/2c64057451ad2bbf58b5aa69b3556177d76c33d2/mmdet/models/roi_heads/bbox_heads/dii_drmm_head.py#L281) is for the mini-batch control. 




If I've misunderstood your question, or if something still remains unclear, please leave more questions :)

**Comment by anilbatra2185** [comment]
thank you @lhj815 for detailed clarification. things are more clear to me now.
